name: BonusMiner
version: 1.0-SNAPSHOT
main: io.github.yourname.bonusminer.BonusMiner # 务必检查这行！
api-version: '1.20'
depend: [Slimefun]
authors: [YourName]
description: 一个具有高爆率功能的附魔工业矿机

commands:
  bmreload:
    description: 重载插件配置
    usage: /<command>
    permission: bonusminer.admin
permissions:
  bonusminer.admin:
    description: 允许重载插件配置
    default: op
